In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Telco-Customer-Churn.csv')

In [3]:
dataset.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
X = dataset.iloc[:,].values

In [5]:
y = dataset.iloc[:, 20].values

In [6]:
print(X)
print(y)

[['7590-VHVEG' 'Female' 0 ... 29.85 '29.85' 'No']
 ['5575-GNVDE' 'Male' 0 ... 56.95 '1889.5' 'No']
 ['3668-QPYBK' 'Male' 0 ... 53.85 '108.15' 'Yes']
 ...
 ['4801-JZAZL' 'Female' 0 ... 29.6 '346.45' 'No']
 ['8361-LTMKD' 'Male' 1 ... 74.4 '306.6' 'Yes']
 ['3186-AJIEK' 'Male' 0 ... 105.65 '6844.5' 'No']]
['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [8]:
labelencoder_X_0 = LabelEncoder()

In [9]:
X[:, 0] = labelencoder_X_0.fit_transform(X[:, 0])

In [10]:
labelencoder_X_1 = LabelEncoder()

In [11]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [12]:
labelencoder_X_2 = LabelEncoder()

In [13]:
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [14]:
labelencoder_X_3 = LabelEncoder()

In [15]:
X[:, 3] = labelencoder_X_3.fit_transform(X[:, 3])

In [16]:
labelencoder_X_4 = LabelEncoder()

In [17]:
X[:, 4] = labelencoder_X_4.fit_transform(X[:, 4])

In [18]:
labelencoder_X_5 = LabelEncoder()

In [19]:
X[:, 5] = labelencoder_X_5.fit_transform(X[:, 5])

In [20]:
labelencoder_X_6 = LabelEncoder()

In [21]:
X[:, 6] = labelencoder_X_6.fit_transform(X[:, 6])

In [22]:
labelencoder_X_7 = LabelEncoder()

In [23]:
X[:, 7] = labelencoder_X_7.fit_transform(X[:, 7])

In [24]:
labelencoder_X_8 = LabelEncoder()

In [25]:
X[:, 8] = labelencoder_X_8.fit_transform(X[:, 8])

In [26]:
labelencoder_X_9 = LabelEncoder()

In [27]:
X[:, 9] = labelencoder_X_9.fit_transform(X[:, 9])

In [28]:
labelencoder_X_10 = LabelEncoder()

In [29]:
X[:, 10] = labelencoder_X_10.fit_transform(X[:, 10])

In [30]:
labelencoder_X_11 = LabelEncoder()

In [31]:
X[:, 11] = labelencoder_X_11.fit_transform(X[:, 11])

In [32]:
labelencoder_X_12 = LabelEncoder()

In [33]:
X[:, 12] = labelencoder_X_12.fit_transform(X[:, 12])

In [34]:
labelencoder_X_13 = LabelEncoder()

In [35]:
X[:, 13] = labelencoder_X_13.fit_transform(X[:, 13])

In [36]:
labelencoder_X_14 = LabelEncoder()

In [37]:
X[:, 14] = labelencoder_X_14.fit_transform(X[:, 14])

In [38]:
labelencoder_X_15 = LabelEncoder()

In [39]:
X[:, 15] = labelencoder_X_15.fit_transform(X[:, 15])

In [40]:
labelencoder_X_16 = LabelEncoder()

In [41]:
X[:, 16] = labelencoder_X_16.fit_transform(X[:, 16])

In [42]:
labelencoder_X_17 = LabelEncoder()

In [43]:
X[:, 17] = labelencoder_X_17.fit_transform(X[:, 17])

In [44]:
labelencoder_X_18 = LabelEncoder()

In [45]:
X[:, 18] = labelencoder_X_18.fit_transform(X[:, 18])

In [46]:
labelencoder_X_19 = LabelEncoder()

In [47]:
X[:, 19] = labelencoder_X_19.fit_transform(X[:, 19])

In [48]:
labelencoder_X_20 = LabelEncoder()

In [49]:
X[:, 20] = labelencoder_X_20.fit_transform(X[:, 20])

In [50]:
print(X)
print(y)

[[5375 0 0 ... 142 2505 0]
 [3962 1 0 ... 498 1466 0]
 [2564 1 0 ... 436 157 1]
 ...
 [3367 0 0 ... 137 2994 0]
 [5934 1 1 ... 795 2660 1]
 [2226 1 0 ... 1388 5407 0]]
['No' 'No' 'Yes' ... 'No' 'Yes' 'No']


In [66]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\Users\Error\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Error\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [53]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
import keras

Using TensorFlow backend.


In [55]:
from keras.models import Sequential

In [56]:
from keras.layers import Dense

In [57]:
classifier = Sequential()

In [59]:
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu', input_dim = 20))

C:\Users\Error\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=20, units=10, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [60]:
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'relu'))

C:\Users\Error\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=10, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [61]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\Error\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [62]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [67]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\Users\Error\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


ValueError: Error when checking input: expected dense_2_input to have shape (20,) but got array with shape (21,)

In [64]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

ValueError: Error when checking input: expected dense_2_input to have shape (20,) but got array with shape (21,)

In [ ]:
print(y_pred)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
print(accuracy)